kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: package-tez
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hadoop-sandbox-package-tez
