apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookage-package-tez
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/zookage/tez
  storageClassName: zookage-package-tez
