apiVersion: v1
kind: Service
metadata:
  name: hive-hiveserver2
spec:
  type: LoadBalancer
  selector: {}
  ports:
  - name: thrift
    port: 10000
  - name: thrift-http
    port: 10001
  - name: webui
    port: 10002
