apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-nodemanager
spec:
  selector:
    matchLabels: {}
  serviceName: yarn-nodemanager
  podManagementPolicy: Parallel
  replicas: 3
  template:
    spec:
      initContainers:
      - name: wait-for-resourcemanager
        image: hadoop-sandbox-main
        args:
        - wait-for-rollout
        - statefulset/yarn-resourcemanager
      containers:
      - name: nodemanager
        image: hadoop-sandbox-main
        args:
        - yarn-nodemanager
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_CLASSPATH
          value: /opt/tez/share/tez-aux-services.jar
        readinessProbe:
          tcpSocket:
            port: 8041
        securityContext:
          runAsUser: 1003
          runAsGroup: 1000
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
        - name: package-hadoop
          mountPath: /opt/hadoop
        - name: package-tez
          mountPath: /opt/tez
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: hadoop-metrics2.properties
            path: hadoop-metrics2.properties
          - key: log4j.properties
            path: log4j.properties
          - key: yarn-site.xml
            path: yarn-site.xml
      - name: mnt
        emptyDir: {}
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
      - name: package-tez
        persistentVolumeClaim:
          claimName: package-tez
  volumeClaimTemplates: []
