apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  selector:
    matchLabels: {}
  serviceName: hdfs-namenode
  replicas: 1
  template:
    spec:
      containers:
      - name: namenode
        image: hadoop-sandbox-main
        args:
        - hdfs-namenode
        envFrom:
        - configMapRef:
            name: hadoop-env
        readinessProbe:
          tcpSocket:
            port: 9820
        securityContext:
          runAsUser: 1011
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
        - name: package-hadoop
          mountPath: /opt/hadoop
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: hadoop-metrics2.properties
            path: hadoop-metrics2.properties
          - key: hdfs-site.xml
            path: hdfs-site.xml
          - key: log4j.properties
            path: log4j.properties
      - name: mnt
        emptyDir: {}
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
  volumeClaimTemplates: []
