apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapreduce-historyserver
spec:
  selector:
    matchLabels: {}
  serviceName: mapreduce-historyserver
  replicas: 1
  template:
    spec:
      initContainers:
      - name: wait-for-history-dir
        image: hadoop-sandbox-main
        args:
        - wait-for-job
        - hdfs-setup
      containers:
      - name: historyserver
        image: hadoop-sandbox-main
        args:
        - mapreduce-historyserver
        envFrom:
        - configMapRef:
            name: hadoop-env
        readinessProbe:
          tcpSocket:
            port: 10020
        securityContext:
          runAsUser: 1013
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
        - name: package-hadoop
          mountPath: /opt/hadoop
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: hadoop-metrics2.properties
            path: hadoop-metrics2.properties
          - key: log4j.properties
            path: log4j.properties
          - key: mapred-site.xml
            path: mapred-site.xml
      - name: mnt
        emptyDir: {}
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
  volumeClaimTemplates: []
