kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: package-hadoop
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: zookage-package-hadoop
