apiVersion: batch/v1
kind: Job
metadata:
  name: tez-deploy
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-apps-dir
        image: zookage-util
        args:
        - wait-for-job
        - hdfs-setup
      - name: wait-for-datanode
        image: zookage-util
        args:
        - wait-for-rollout
        - statefulset/hdfs-datanode
      - name: upload
        image: zookage-util
        command:
        - /opt/hadoop/bin/hdfs
        args:
        - dfs
        - -copyFromLocal
        - /opt/tez/share/tez-minimal.tar.gz
        - hdfs:///apps/tez/tez-minimal.tar.gz
        envFrom:
        - configMapRef:
            name: hadoop-env
        securityContext:
          runAsUser: 1011
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: package-hadoop
          mountPath: /opt/hadoop
        - name: package-tez
          mountPath: /opt/tez
      containers:
      - name: chown
        image: zookage-util
        command:
        - gohdfs
        args:
        - chown
        - tez:tez
        - hdfs:///apps/tez/tez-minimal.tar.gz
        envFrom:
        - configMapRef:
            name: hadoop-env
        securityContext:
          runAsUser: 1011
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      restartPolicy: Never
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
      - name: package-tez
        persistentVolumeClaim:
          claimName: package-tez
