apiVersion: batch/v1
kind: Job
metadata:
  name: tez-deploy
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-apps-dir
        image: hadoop-sandbox-main
        args:
        - wait-for-job
        - hdfs-setup
      - name: wait-for-datanode
        image: hadoop-sandbox-main
        args:
        - wait-for-rollout
        - statefulset/hdfs-datanode
      containers:
      - name: deploy
        image: hadoop-sandbox-main
        args:
        - tez-deploy
        envFrom:
        - configMapRef:
            name: hadoop-env
        securityContext:
          runAsUser: 1011
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: package-hadoop
          mountPath: /opt/hadoop
        - name: package-tez
          mountPath: /opt/tez
      restartPolicy: Never
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
      - name: package-tez
        persistentVolumeClaim:
          claimName: package-tez
