apiVersion: batch/v1
kind: Job
metadata:
  name: hdfs-setup
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-namenode
        image: hadoop-sandbox-main
        args:
        - wait-for-rollout
        - statefulset/hdfs-namenode
      containers:
      - name: setup
        image: hadoop-sandbox-main
        args:
        - hdfs-setup
        envFrom:
        - configMapRef:
            name: hadoop-env
        securityContext:
          runAsUser: 1011
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      restartPolicy: Never
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: log4j.properties
            path: log4j.properties
      - name: mnt
        emptyDir: {}
