apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-resourcemanager
spec:
  selector:
    matchLabels: {}
  serviceName: yarn-resourcemanager
  replicas: 1
  template:
    spec:
      containers:
      - name: resourcemanager
        image: zookage-util
        command:
        - /opt/hadoop/bin/yarn
        args:
        - resourcemanager
        envFrom:
        - configMapRef:
            name: hadoop-env
        readinessProbe:
          tcpSocket:
            port: 8032
        securityContext:
          runAsUser: 1012
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
        - name: package-hadoop
          mountPath: /opt/hadoop
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
  volumeClaimTemplates: []
