namespace: hadoop-sandbox
bases:
- base
resources:
- namespace.yaml
images:
- name: hadoop-sandbox-hadoop
  newName: hadoopsandbox/hadoop-sandbox-hadoop
  newTag: "3.1.3"
- name: hadoop-sandbox-hive
  newName: hadoopsandbox/hadoop-sandbox-hive
  newTag: "3.1.2-guava-27.0-jre"
- name: hadoop-sandbox-tez
  newName: hadoopsandbox/hadoop-sandbox-tez
  newTag: "0.9.2-guava-27.0-jre-jersey-1.19"
- name: hadoop-sandbox-main
  newName: hadoopsandbox/hadoop-sandbox-main
  newTag: "master"
