apiVersion: batch/v1
kind: Job
metadata:
  name: package-hive
spec:
  template:
    spec:
      containers:
      - name: hadoop-sandbox-hive
        image: hadoop-sandbox-hive
        command:
        - /bin/bash
        args:
        - -c
        - "rm -rf /mnt/hadoop-sandbox/hive && cp -R /opt/hive /mnt/hadoop-sandbox/hive"
        volumeMounts:
        - name: package-home
          mountPath: /mnt/hadoop-sandbox
      restartPolicy: Never
      volumes:
      - name: package-home
        hostPath:
          path: /opt/hadoop-sandbox
