kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: package-hive
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: hadoop-sandbox-package-hive
